<?php
add_filter( 'prima_design_settings_args', 'prima_design_general_settings', 5 );
function prima_design_general_settings( $settings ) {
	$settings[] = array( "name" => __('General', 'primathemes'),
						"icon" => "general",
						"type" => "heading");
		$settings["style"] = array( "name" => __('Style Layout', 'primathemes'),
							"desc" => "",
							"id" => "style",
							"type" => "select2",
							"std" => "boxed",
							"options" => array(
								'boxed' => __('Boxed', 'primathemes'),
								'full' => __('Full', 'primathemes'),
								'simple' => __('Simple', 'primathemes')
							) );
		$settings["responsive"] = array( "name" => __('Responsive Layout', 'primathemes'),
							"desc" => __('Users now use mobile phones, small notebooks, tablet devices such as iPad or Playbook to access the web. The layout needs is automatically adjusted to fit all display resolution and devices.', 'primathemes'),
							"id" => "responsive",
							"type" => "select2",
							"std" => "yes",
							"options" => array(
								'yes' => __('Yes', 'primathemes'),
								'no' => __('No', 'primathemes')
							) );
		$settings[] = array( "name" => __('I am responsive!', 'primathemes'),
							"desc" => __('Show &quot;resize image&quot; at the left bottom to show that your website is responsive!', 'primathemes'),
							"id" => "responsive_image",
							"type" => "select2",
							"std" => "yes",
							"options" => array(
								'yes' => __('Yes', 'primathemes'),
								'no' => __('No', 'primathemes')
							) );
		$settings[] = array( "name" => __('Body Background', 'primathemes'),
							"desc" => "",
							"id" => "body_background",
							"std" => "",
							"selector" => 'body',
							"type" => "background");
		$settings[] = array( "name" => __('Body Paragraph Color', 'primathemes'),
							"desc" => "",
							"id" => "body_color",
							"std" => "",
							"selector" => 'body',
							"type" => "color");
		$settings[] = array( "name" => __('Body Heading Color', 'primathemes'),
							"desc" => "",
							"id" => "body_heading",
							"std" => "",
							"selector" => "h1,h2,h3,h4,h5",
							"type" => "color");
		$settings[] = array( "name" => __('Default Link Color', 'primathemes'),
							"desc" => "",
							"id" => "body_link",
							"std" => "",
							"selector" => "a,a:visited",
							"type" => "color");
		$settings[] = array( "name" => __('Default Link Color (Hover)', 'primathemes'),
							"desc" => "",
							"id" => "body_linkhover",
							"std" => "",
							"selector" => "a:hover",
							"type" => "color");
		$settings[] = array( "name" => __('Container Border Top', 'primathemes'),
							"desc" => "",
							"id" => "container_bordertop",
							"std" => "",
							"selector" => "body.stylelayout-boxed #container .containerInner, body.stylelayout-full #container .containerInner, body.stylelayout-simple #container",
							"attribute" => "border-top",
							"type" => "border");
		$settings[] = array( "name" => __('Container Border Bottom', 'primathemes'),
							"desc" => "",
							"id" => "container_borderbottom",
							"std" => "",
							"selector" => "body.stylelayout-boxed #container .containerInner, body.stylelayout-full #container .containerInner, body.stylelayout-simple #container",
							"attribute" => "border-bottom",
							"type" => "border");
	$settings[] = array( "name" => __('Typography', 'primathemes'),
						"icon" => "typography",
						"type" => "heading");
		$settings[] = array( "name" => __('Section / Horizontal Heading Background Color', 'primathemes'),
							"desc" => "",
							"id" => "section_bgcolor",
							"std" => "",
							"selector" => '.section h2 span, h2.horizontalheading span',
							"attribute" => 'background-color',
							"type" => "color");
		$settings[] = array( "name" => __('Section / Horizontal Heading Text Color', 'primathemes'),
							"desc" => "",
							"id" => "section_textcolor",
							"std" => "",
							"selector" => '.section h2 span, h2.horizontalheading span',
							"attribute" => 'color',
							"type" => "color");
		$settings[] = array( "name" => __('Section / Horizontal Heading Line Color', 'primathemes'),
							"desc" => "",
							"id" => "section_linecolor",
							"std" => "",
							"selector" => '.section h2, h2.horizontalheading',
							"attribute" => 'border-color',
							"type" => "color");
		$settings[] = array( "name" => __('Price Text Color', 'primathemes'),
							"desc" => "",
							"id" => "price_textcolor",
							"std" => "",
							"selector" => '.price, div.product div.summary .price',
							"attribute" => 'color',
							"type" => "color");
		$settings[] = array( "name" => __('Normal Price Text Color', 'primathemes'),
							"desc" => "",
							"id" => "pricenormal_textcolor",
							"std" => "",
							"selector" => '.price del',
							"attribute" => 'color',
							"type" => "color");
		$settings[] = array( "name" => __('Sale Price Text Color', 'primathemes'),
							"desc" => "",
							"id" => "pricesale_textcolor",
							"std" => "",
							"selector" => '.price ins',
							"attribute" => 'color',
							"type" => "color");
		$settings[] = array( "name" => __('Variation Price Prefix ( ex: &quot;from&quot; ) Text Color', 'primathemes'),
							"desc" => "",
							"id" => "pricefrom_textcolor",
							"std" => "",
							"selector" => '.price .from',
							"attribute" => 'color',
							"type" => "color");
		$settings[] = array( "name" => __('Sale Flash Background Color', 'primathemes'),
							"desc" => "",
							"id" => "saleflash_bgcolor",
							"std" => "",
							"selector" => 'span.onsale',
							"attribute" => 'background-color',
							"type" => "color");
		$settings[] = array( "name" => __('Sale Flash Text Color', 'primathemes'),
							"desc" => "",
							"id" => "saleflash_textcolor",
							"std" => "",
							"selector" => 'span.onsale',
							"attribute" => 'color',
							"type" => "color");
		$settings[] = array( "name" => __('Add To Cart Button Background Color', 'primathemes'),
							"desc" => "",
							"id" => "addtocart_bgcolor",
							"std" => "",
							"selector" => 'div.product div.summary button.button, div.product div.summary a.button',
							"attribute" => 'background-color',
							"type" => "color");
		$settings[] = array( "name" => __('Add To Cart Button Text Color', 'primathemes'),
							"desc" => "",
							"id" => "addtocart_textcolor",
							"std" => "",
							"selector" => 'div.product div.summary button.button, div.product div.summary a.button',
							"attribute" => 'color',
							"important" => true,
							"type" => "color");
		$settings[] = array( "name" => __('Add To Cart Button Background Color (Hover)', 'primathemes'),
							"desc" => "",
							"id" => "addtocart_bgcolorhover",
							"std" => "",
							"selector" => 'div.product div.summary button.button:hover, div.product div.summary a.button:hover',
							"attribute" => 'background-color',
							"type" => "color");
		$settings[] = array( "name" => __('Add To Cart Button Text Color (Hover)', 'primathemes'),
							"desc" => "",
							"id" => "addtocart_textcolorhover",
							"std" => "",
							"selector" => 'div.product div.summary button.button:hover, div.product div.summary a.button:hover',
							"attribute" => 'color',
							"important" => true,
							"type" => "color");
		$settings[] = array( "name" => __('Product Data Tabs Background Color', 'primathemes'),
							"desc" => "",
							"id" => "producttabs_bgcolor",
							"std" => "",
							"selector" => 'div.product .woocommerce_tabs ul.tabs',
							"attribute" => 'background-color',
							"type" => "color");
	$settings[] = array( "name" => __('Boxed', 'primathemes'),
						"icon" => "boxed",
						"type" => "heading");
		$settings[] = array( "name" => __('Note:', 'primathemes'),
							"std" => __( 'Boxed settings is dedicated for <b>Boxed</b> Style Layout at General Settings page!', 'primathemes' ),
							"type" => "info");
		$settings[] = array( "name" => __('Boxed Background', 'primathemes'),
							"desc" => "",
							"id" => "boxed_background",
							"std" => "",
							"selector" => 'body.stylelayout-boxed #container .containerInner',
							"type" => "background");
	$settings[] = array( "name" => __('Top Navigation', 'primathemes'),
						"icon" => "topnav",
						"type" => "heading");
		$settings[] = array( "name" => __('Top Navigation Background', 'primathemes'),
							"desc" => "",
							"id" => "topnav_background",
							"std" => "",
							"selector" => '#topnav',
							"type" => "background");
		$settings[] = array( "name" => __('Top Navigation Border Bottom', 'primathemes'),
							"desc" => "",
							"id" => "topnav_borderbottom",
							"std" => "",
							"selector" => '#topnav',
							"attribute" => 'border-bottom',
							"type" => "border");
		$settings[] = array( "name" => __('Top Ticker Color', 'primathemes'),
							"desc" => "",
							"id" => "topticker_color",
							"std" => "",
							"selector" => '#topticker li a',
							"type" => "color");
		$settings[] = array( "name" => __('Top Menu Color', 'primathemes'),
							"desc" => "",
							"id" => "topmenu_color",
							"std" => "",
							"selector" => 'ul#topnavmenu li.menu-item a',
							"type" => "color");
		$settings[] = array( "name" => __('Top Menu Color (Hover)', 'primathemes'),
							"desc" => "",
							"id" => "topmenu_colorhover",
							"std" => "",
							"selector" => 'ul#topnavmenu li.menu-item a:hover',
							"type" => "color");
		$settings[] = array( "name" => __('Mini Shopping Cart Link Color', 'primathemes'),
							"desc" => "",
							"id" => "minicart_color",
							"std" => "",
							"selector" => 'ul#topnavmenu li#basketlink a.basket, ul#topnavmenu li#basketlink:hover a.basket',
							"type" => "color");
		$settings[] = array( "name" => __('Mini Shopping Cart Background', 'primathemes'),
							"desc" => "",
							"id" => "minicart_background",
							"std" => "",
							"selector" => '#minicart',
							"type" => "background");
	$settings[] = array( "name" => __('Logo + Header Menu', 'primathemes'),
						"icon" => "logo",
						"type" => "heading");
		$settings[] = array( "name" => __('Logo + Header Menu Background', 'primathemes'),
							"desc" => "",
							"id" => "primary_background",
							"std" => "",
							"selector" => 'nav#primary',
							"type" => "background");
		$settings[] = array( "name" => __('Logo + Header Menu Border Bottom', 'primathemes'),
							"desc" => "",
							"id" => "primary_borderbottom",
							"std" => "",
							"selector" => 'nav#primary',
							"attribute" => 'border-bottom',
							"type" => "border");
		$settings[] = array( "name" => __('Logo Title Color', 'primathemes'),
							"desc" => "",
							"id" => "logotitle_color",
							"std" => "",
							"selector" => '#primarylogo, #primarylogo a',
							"type" => "color");
		$settings[] = array( "name" => __('Logo Title Color (Hover)', 'primathemes'),
							"desc" => "",
							"id" => "logotitle_colorhover",
							"std" => "",
							"selector" => '#primarylogo a:hover',
							"type" => "color");
		$settings[] = array( "name" => __('Header Menu Color', 'primathemes'),
							"desc" => "",
							"id" => "headermenu_color",
							"std" => "",
							"selector" => 'nav#primary ul.sf-menu li a',
							"type" => "color");
		$settings[] = array( "name" => __('Header Menu Color (Hover)', 'primathemes'),
							"desc" => "",
							"id" => "headermenu_colorhover",
							"std" => "",
							"selector" => 'nav#primary ul.sf-menu li a:hover, nav#primary ul.sf-menu li.sfHover a',
							"type" => "color");
		$settings[] = array( "name" => __('Header Menu Color (Current)', 'primathemes'),
							"desc" => "",
							"id" => "headermenu_colorcurrent",
							"std" => "",
							"selector" => 'nav#primary ul.sf-menu li.current-menu-ancestor a, nav#primary ul.sf-menu li.current-menu-item a',
							"type" => "color");
		$settings[] = array( "name" => __('Header Submenu Background', 'primathemes'),
							"desc" => "",
							"id" => "headersubmenu_background",
							"std" => "",
							"selector" => 'nav#primary ul.sf-menu li ul.sub-menu',
							"type" => "background");
		$settings[] = array( "name" => __('Header Submenu Color', 'primathemes'),
							"desc" => "",
							"id" => "headersubmenu_color",
							"std" => "",
							"selector" => 'nav#primary ul.sf-menu li ul.sub-menu li a',
							"type" => "color");
		$settings[] = array( "name" => __('Header Submenu Color (Hover)', 'primathemes'),
							"desc" => "",
							"id" => "headersubmenu_colorhover",
							"std" => "",
							"selector" => 'nav#primary ul.sf-menu li ul.sub-menu li a:hover',
							"type" => "color");
	$settings[] = array( "name" => __('Header', 'primathemes'),
						"icon" => "header",
						"type" => "heading");
		$settings[] = array( "name" => __('Header Background', 'primathemes'),
							"desc" => "",
							"id" => "header_bg",
							"std" => "",
							"selector" => "#header",
							"type" => "background");
		$settings[] = array( "name" => __('Header Border Top', 'primathemes'),
							"desc" => "",
							"id" => "header_bordertop",
							"std" => "",
							"selector" => '#header',
							"attribute" => "border-top",
							"type" => "border");
		$settings[] = array( "name" => __('Header Border Bottom', 'primathemes'),
							"desc" => "",
							"id" => "header_borderbottom",
							"std" => "",
							"selector" => '#header',
							"attribute" => "border-bottom",
							"type" => "border");
		$settings[] = array( "name" => __('Header Heading Color', 'primathemes'),
							"desc" => "",
							"id" => "header_heading",
							"std" => "",
							"selector" => "#header h1, #header h2, #header #headercustom h1, #header #headercustom h2, #headersubcategories ul li h5",
							"type" => "color");
		$settings[] = array( "name" => __('Header Text Color', 'primathemes'),
							"desc" => "",
							"id" => "header_color",
							"std" => "",
							"selector" => "#header",
							"type" => "color");
		$settings[] = array( "name" => __('Header Link Color', 'primathemes'),
							"desc" => "",
							"id" => "header_link",
							"std" => "",
							"selector" => "#header a,#header a:hover",
							"type" => "color");
		$settings[] = array( "name" => __('Header Search Form Background Color', 'primathemes'),
							"desc" => "",
							"id" => "headersearch_bgcolor",
							"std" => "",
							"selector" => "#header #headersearchform input.searchinput",
							"attribute" => "background-color",
							"type" => "color");
		$settings[] = array( "name" => __('Header Search Form Text Color', 'primathemes'),
							"desc" => "",
							"id" => "headersearch_color",
							"std" => "",
							"selector" => "#header #headersearchform input.searchinput",
							"type" => "color");
		$settings[] = array( "name" => __('Header Search Form Border', 'primathemes'),
							"desc" => "",
							"id" => "headersearch_border",
							"std" => "",
							"selector" => '#header #headersearchform input.searchinput',
							"type" => "border");
	$settings[] = array( "name" => __('Footer Top', 'primathemes'),
						"icon" => "content",
						"type" => "heading");
		$settings[] = array( "name" => __('Footer Top Background', 'primathemes'),
							"desc" => "",
							"id" => "footertop_bg",
							"std" => "",
							"selector" => "#footertop",
							"type" => "background");
		$settings[] = array( "name" => __('Footer Top Border Top', 'primathemes'),
							"desc" => "",
							"id" => "footertop_bordertop",
							"std" => "",
							"selector" => '#footertop',
							"attribute" => "border-top",
							"type" => "border");
		$settings[] = array( "name" => __('Footer Top Border Bottom', 'primathemes'),
							"desc" => "",
							"id" => "footertop_borderbottom",
							"std" => "",
							"selector" => '#footertop',
							"attribute" => "border-bottom",
							"type" => "border");
		$settings[] = array( "name" => __('Footer Top Text Color', 'primathemes'),
							"desc" => "",
							"id" => "footertop_color",
							"std" => "",
							"selector" => "#footertop",
							"type" => "color");
		$settings[] = array( "name" => __('Footer Top Link Color', 'primathemes'),
							"desc" => "",
							"id" => "footertop_link",
							"std" => "",
							"selector" => "#footertop a",
							"type" => "color");
		$settings[] = array( "name" => __('Footer Top Link Color (Hover)', 'primathemes'),
							"desc" => "",
							"id" => "footertop_linkhover",
							"std" => "",
							"selector" => "#footertop a:hover",
							"type" => "color");
		$settings[] = array( "name" => __('Footer Top Heading Color', 'primathemes'),
							"desc" => "",
							"id" => "footertop_heading",
							"std" => "",
							"selector" => "#footertop h2, #footertop h3, #footertop h4, #footertop h5, #footertop h5, #footertop h3.widget-title",
							"type" => "color");
	$settings[] = array( "name" => __('Footer Bottom', 'primathemes'),
						"icon" => "content",
						"type" => "heading");
		$settings[] = array( "name" => __('Footer Bottom Background', 'primathemes'),
							"desc" => "",
							"id" => "footerbottom_bg",
							"std" => "",
							"selector" => "#footerbottom",
							"type" => "background");
		$settings[] = array( "name" => __('Footer Bottom Border Top', 'primathemes'),
							"desc" => "",
							"id" => "footerbottom_bordertop",
							"std" => "",
							"selector" => '#footerbottom',
							"attribute" => "border-top",
							"type" => "border");
		$settings[] = array( "name" => __('Footer Bottom Border Bottom', 'primathemes'),
							"desc" => "",
							"id" => "footerbottom_borderbottom",
							"std" => "",
							"selector" => '#footerbottom',
							"attribute" => "border-bottom",
							"type" => "border");
		$settings[] = array( "name" => __('Footer Bottom Text Color', 'primathemes'),
							"desc" => "",
							"id" => "footerbottom_color",
							"std" => "",
							"selector" => "#footerbottom",
							"type" => "color");
		$settings[] = array( "name" => __('Footer Bottom Link Color', 'primathemes'),
							"desc" => "",
							"id" => "footerbottom_link",
							"std" => "",
							"selector" => "#footerbottom a",
							"type" => "color");
		$settings[] = array( "name" => __('Footer Bottom Link Color (Hover)', 'primathemes'),
							"desc" => "",
							"id" => "footerbottom_linkhover",
							"std" => "",
							"selector" => "#footerbottom a:hover",
							"type" => "color");
		$settings[] = array( "name" => __('Footer Bottom Heading Color', 'primathemes'),
							"desc" => "",
							"id" => "footerbottom_heading",
							"std" => "",
							"selector" => "#footerbottom h2, #footerbottom h3, #footerbottom h4, #footerbottom h5, #footerbottom h5, #footerbottom h3.widget-title",
							"type" => "color");
	$settings[] = array( "name" => __('Footer Credits', 'primathemes'),
						"icon" => "footer",
						"type" => "heading");
		$settings[] = array( "name" => __('Footer Credits Background', 'primathemes'),
							"desc" => "",
							"id" => "footercredits_bg",
							"std" => "",
							"selector" => "#footercredits",
							"type" => "background");
		$settings[] = array( "name" => __('Footer Credits Border Top', 'primathemes'),
							"desc" => "",
							"id" => "footercredits_bordertop",
							"std" => "",
							"selector" => '#footercredits',
							"attribute" => "border-top",
							"type" => "border");
		$settings[] = array( "name" => __('Footer Credits Border Bottom', 'primathemes'),
							"desc" => "",
							"id" => "footercredits_borderbottom",
							"std" => "",
							"selector" => '#footercredits',
							"attribute" => "border-bottom",
							"type" => "border");
		$settings[] = array( "name" => __('Footer Credits Text Color', 'primathemes'),
							"desc" => "",
							"id" => "footercredits_color",
							"std" => "",
							"selector" => "#footercredits",
							"type" => "color");
		$settings[] = array( "name" => __('Footer Credits Link Color', 'primathemes'),
							"desc" => "",
							"id" => "footercredits_link",
							"std" => "",
							"selector" => "#footercredits a",
							"type" => "color");
		$settings[] = array( "name" => __('Footer Credits Link Color (Hover)', 'primathemes'),
							"desc" => "",
							"id" => "footercredits_linkhover",
							"std" => "",
							"selector" => "#footercredits a:hover",
							"type" => "color");
	$settings[] = array( "name" => __('Font Settings', 'primathemes'),
						"icon" => "font",
						"type" => "heading");
		$settings[] = array( "name" => __('Heading Font', 'primathemes'),
							"desc" => "",
							"id" => "font_heading",
							"std" => "opensans",
							"selector" => "h1,h2,h3,h4,h5,h6,nav#primary ul.sf-menu,article.postblog p.postmeta,span.onsale",
							"type" => "font");
		$settings[] = array( "name" => __('Body Font', 'primathemes'),
							"desc" => "",
							"id" => "font_body",
							"std" => "",
							"selector" => "body,button, input, select, textarea",
							"type" => "font");
	return $settings;
}

add_filter( 'prima_googlefonts', 'prima_custom_googlefonts', 5 );
function prima_custom_googlefonts($googlefonts) {
	$googlefonts['opensans'] = array(
			'value' =>	'opensans',
			'label' =>  'Open Sans',
			'type' =>  'google',
			'font' =>	'Open Sans',
			'style' =>  '400italic,300,400,600'
		);
	return $googlefonts;
}