<?php
/*
 WARNING: This file is part of the core PrimaThemes framework. 
 DO NOT edit this file under any circumstances. 
 Please do all modifications in the form of a child theme.
 */
require_once( TEMPLATEPATH.'/core/functions/setup.php' );
require_once(TEMPLATEPATH.'/functions/ev_breadcrumbs.php');
require_once(TEMPLATEPATH.'/functions/ev_google_map.php');
require_once(TEMPLATEPATH.'/functions/ev_faq_shortcode.php');
